# Generated by Django 5.2.6 on 2025-10-22 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=100)),
                ('telefone_cliente', models.CharField(max_length=20)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('quantidade_pessoas', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=10)),
            ],
        ),
    ]
