# Generated by Django 5.2.6 on 2025-10-25 00:03

# Correção: Removido import 'datetime' não utilizado aqui
# Correção: Adicionado import 'django.utils.timezone' se fosse necessário default timezone.now
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
# Correção: Se fosse usar timezone.now() como default, precisaria disso:
# from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='nome_cliente',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='telefone_cliente',
        ),
        migrations.AddField(
            model_name='reserva',
            name='timestamp_criacao',
            # Usar django.utils.timezone.now para default é mais seguro que datetime.datetime
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now), # Default ajustado
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='usuario',
            # --- CORREÇÃO AQUI: Adicionado null=True ---
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL),
            # --- FIM DA CORREÇÃO ---
            preserve_default=False,
        ),
    ]