# Generated by Django 5.2.7 on 2025-10-26 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fila', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientefila',
            name='timestamp_atendimento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientefila',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientefila',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clientefila',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO', 'Aguardando'), ('CHAMADO', 'Chamado'), ('CANCELADO', 'Cancelado/Desistiu')], default='AGUARDANDO', max_length=10),
        ),
        migrations.AlterField(
            model_name='clientefila',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
