# Generated by Django 5.2.6 on 2025-10-24 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comanda',
            name='mesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comandas', to='comandas.mesa'),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='status',
            field=models.CharField(choices=[('LIVRE', 'Livre'), ('OCUPADA', 'Ocupada'), ('PAGAMENTO', 'Pagamento')], default='LIVRE', max_length=10),
        ),
    ]
