# Generated by Django 5.2.6 on 2025-10-24 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0002_alter_comanda_mesa_alter_mesa_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcomanda',
            name='observacao',
            field=models.TextField(blank=True, help_text='Ex: Sem cebola, ponto da carne', null=True),
        ),
    ]
