# Generated by Django 5.2.6 on 2025-10-27 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0002_alter_categoria_options_alter_itemcardapio_options_and_more'),
        ('comandas', '0003_itemcomanda_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcomanda',
            name='item_cardapio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cardapio.itemcardapio'),
        ),
    ]
