# Generated by Django 5.2.6 on 2025-10-17 23:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteFila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('quantidade', models.PositiveIntegerField()),
                ('timestamp_entrada', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('AGUARDANDO', 'Aguardando'), ('CHAMADO', 'Chamado'), ('CANCELADO', 'Cancelado')], default='AGUARDANDO', max_length=10)),
            ],
        ),
    ]
