# Generated by Django 5.2.6 on 2025-10-27 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Coca-Cola Lata 350ml, Garrafa Vinho Tinto X, Dose Jack Daniels', max_length=150, unique=True)),
                ('quantidade_atual', models.IntegerField(default=0, help_text='Quantidade atual em unidades.')),
                ('ponto_reposicao', models.PositiveIntegerField(blank=True, default=10, help_text='Quantidade mínima para alerta de reposição.', null=True)),
            ],
            options={
                'verbose_name': 'Item em Estoque',
                'verbose_name_plural': 'Itens em Estoque',
                'ordering': ['nome'],
            },
        ),
    ]
