# Generated by Django 5.2.7 on 2025-10-26 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='itemcardapio',
            options={'ordering': ['categoria__nome', 'nome']},
        ),
        migrations.AddField(
            model_name='itemcardapio',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Desmarque para ocultar este item do cardápio público.'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='itemcardapio',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='cardapio.categoria'),
        ),
        migrations.AlterField(
            model_name='itemcardapio',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemcardapio',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='pratos/'),
        ),
    ]
