# Generated by Django 5.2.6 on 2025-10-27 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0002_alter_categoria_options_alter_itemcardapio_options_and_more'),
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcardapio',
            name='item_estoque',
            field=models.ForeignKey(blank=True, help_text='Opcional: Ligue este item do cardápio a um item do estoque para controle.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_cardapio', to='estoque.itemestoque'),
        ),
    ]
